# Change these first
owner: troyervin
repo: treeplex-status

sites:
  - name: TreePlex Server
    url: https://treeplex.ca
    icon: https://raw.githubusercontent.com/troyervin/treeplex-status/master/assets/treeplexicon.ico
  - name: Plex
    url: https://plex.treeplex.ca/web/index.html
    icon: https://raw.githubusercontent.com/troyervin/treeplex-status/master/assets/plexicon.ico
  - name: Emby
    url: https://emby.treeplex.ca/web/index.html
    icon: https://raw.githubusercontent.com/troyervin/treeplex-status/master/assets/embyicon.ico
  - name: Overseerr
    url: https://add.treeplex.ca
    icon: https://raw.githubusercontent.com/troyervin/treeplex-status/master/assets/overseerricon.ico
  - name: HomeAssistant
    url: https://ha.treeplex.ca
    icon: https://raw.githubusercontent.com/troyervin/treeplex-status/master/assets/homeassistanticon.ico

status-website:
  # Domain Settings
  cname: status.treeplex.ca
  # baseUrl: /treeplex-status

  # Branding
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Treeplex Status
  introMessage: Real-time status for Plex, Emby, and Overseerr services

  # CSS Block
  css: |
    body {
      background-image: url('https://raw.githubusercontent.com/troyervin/treeplex-status/master/assets/background.png');
      background-size: cover;
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-position: center;
    }
    .hero { background-color: rgba(0,0,0,0.85) !important; }
    .tabs { background-color: rgba(0,0,0,0.9) !important; }

    /* STEP 1: Make ALL sections transparent by default */
    section {
      background-color: transparent !important;
      box-shadow: none !important;
      padding: 0 !important;
    }

    /* STEP 2: Only paint the dark box on the section that has the Graphs (SVG) */
    section:has(svg) {
      background-color: rgba(0, 0, 0, 0.85) !important;
      padding: 1.5rem !important;
      border-radius: 12px !important;
      box-shadow: 0 4px 6px rgba(0,0,0,0.5) !important;
      margin-top: 2rem !important;
    }

  # Navigation Bar (This is now correctly aligned under status-website)
  navbar:
    - title: TreePlex Home
      href: https://treeplex.ca
    - title: Status
      href: /
