# Change these first
owner: troyervin # Your GitHub organization or username, where this repository lives
repo: treeplex-status # The name of this repository

sites:
  - name: TreePlex
    url: https://treeplex.ca
    icon: https://raw.githubusercontent.com/troyervin/treeplex-status/master/assets/treeplexicon.ico
  - name: Plex
    url: https://plex.treeplex.ca/web/index.html
    icon: https://raw.githubusercontent.com/troyervin/treeplex-status/master/assets/plexicon.ico
  - name: Emby
    url: https://emby.treeplex.ca/web/index.html
    icon: https://raw.githubusercontent.com/troyervin/treeplex-status/master/assets/embyicon.ico
  - name: Overseerr
    url: https://add.treeplex.ca
    icon: https://raw.githubusercontent.com/troyervin/treeplex-status/master/assets/overseerricon.ico
  - name: HomeAssistant
    url: https://ha.treeplex.ca
    icon: https://raw.githubusercontent.com/troyervin/treeplex-status/master/assets/homeassistanticon.ico

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.treeplex.ca
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status.Treeplex.Ca
  introTitle: "**TreePlex Status**"
  introMessage: Real-time status for Plex, Emby, and Overseerr services
  navbar:
    - title: TreePlex Home
      href: https://treeplex.ca
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration 
